my_string = input("Введите строку: ")
print("Количество символов Вашей строки:", len(my_string))
print("Ваша строка в верхнем регистре:", my_string.upper())
print("Ваша строка в нижнем регистре:", my_string.lower())
print("Ваша строка без пробелов:", my_string.replace(" ", ""))
print("Первый символ Вашей строки:", my_string[0])
print("Последний символ Вашей строки:", my_string[-1])
